### ISSUE TITLE
Master branch is not compiling

### ISSUE THREAD

**Issue by paulopinheiro1234** [paulopinheiro1234/hadatac-browser#1]
Error message:

[error] /Users/paulopinheiro/Documents/git/hadatac-browser/app/views/hierarchy_faceting.scala.html:25: not found: value metadata_table
[error]       				@metadata_table(query_results)
[error]       				 ^
[error] /Users/paulopinheiro/Documents/git/hadatac-browser/app/views/metadata_list.scala.html:11: not found: value metadata_table
[error]       		@metadata_table(documentMap)
[error]       		 ^
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 9 s, completed Jul 30, 2015 3:51:57 PM
[

**Comment by chastk** [comment]
Fixed in commit a5f6bf5f23
